name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        yarn deploy
      env:
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        REACT_APP_SPOTIFY_BASE_URL: ${{ secrets.REACT_APP_SPOTIFY_BASE_URL }}
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_SPOTIFY_REDIRECT_URI: ${{ secrets.REACT_APP_SPOTIFY_REDIRECT_URI }}
        REACT_APP_SPOTIFY_SCOPE: ${{ secrets.REACT_APP_SPOTIFY_SCOPE }}
        REACT_APP_SPOTIFY_PING_INTERVAL: ${{ secrets.REACT_APP_SPOTIFY_PING_INTERVAL }}
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        repository: ${{ github.repository }}
